extern const char * car = "<html> "
"<body> "
"<h1> Car Controller! </h1> "
"<p> You can turn on/off LED on ESP by clicking on this button: </p> "
"<button type=\"submit\" id=\"forward\" onClick=\"handleClick(this.id)\"> Forward </button> "
"<button type=\"submit\" id=\"right\" onClick=\"handleClick(this.id)\"> Right </button> "
"<button type=\"submit\" id=\"left\" onClick=\"handleClick(this.id)\"> Left </button> "
"<button type=\"submit\" id=\"backward\" onClick=\"handleClick(this.id)\"> Backward </button> "
"<button type=\"submit\" id=\"stop\" onClick=\"handleClick(this.id)\"> Stop </button> "
"<button type=\"submit\" id=\"add\" onClick=\"handleClick(this.id)\"> Speed + </button> "
"<button type=\"submit\" id=\"sub\" onClick=\"handleClick(this.id)\"> Speed - </button> "
"</body> "
" "
"<script> "
"function handleClick(stateID) { "
"fetch(\"/car?state=\" + stateID, { "
"method: \"GET\" "
"}).then(res => { "
"console.log(\"Request complete! response:\", res); "
"}); "
"} "
"</script> "
"</html> "
"";